In [1]:
%load_ext autoreload
%autoreload 2

import logging
import glob
import pandas as pd

from humun_benchmark.data.metrics import read_results, compute_benchmark_metrics
from humun_benchmark.config import setup_logging

setup_logging()
log = logging.getLogger(__name__)

/Users/aidenlewington/Code/humun/benchmarking/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# No context benchmarks 
paths_no_ctx = glob.glob(f"../benchmarks/llm_zeroshot_no_ctx_20250508_000047/*.parquet")
results_no_ctx = read_results(paths_no_ctx)
metrics_no_ctx = compute_benchmark_metrics(results_no_ctx)
metrics_no_ctx['overall_metrics']

                             WMAPE  CRPS       MAE      RMSE
Model
Llama-3.1-8B-Instruct        7.351  0.80    353.14    451.14
Llama-3.2-1B-Instruct       23.602  1.89  15542.52  28648.61
Llama-3.2-3B-Instruct       11.786  1.06    615.62    905.22
Ministral-8B-Instruct-2410   6.675  0.92    187.51    235.59
Qwen2.5-1.5B-Instruct       14.429  0.64    556.18    773.48
Qwen2.5-3B-Instruct          6.211  0.91    239.08    325.84
Qwen2.5-7B-Instruct          6.613  0.76    226.24    280.10

In [7]:
# Timeseries context provided
paths_ctx = glob.glob(f"../benchmarks/llm_zeroshot_with_ctx_20250508_002944/*.parquet")
results_ctx = read_results(paths_ctx)
metrics_ctx = compute_benchmark_metrics(results_ctx)
metrics_ctx['overall_metrics'].index = metrics_ctx['overall_metrics'].index + " (ctx)"
metrics_ctx['overall_metrics']

                                   WMAPE  CRPS       MAE      RMSE
Model
Llama-3.1-8B-Instruct (ctx)        6.720  0.73    346.06    457.43
Llama-3.2-1B-Instruct (ctx)       32.630  4.33  19170.62  32129.55
Llama-3.2-3B-Instruct (ctx)        7.031  0.50    813.45    926.40
Ministral-8B-Instruct-2410 (ctx)   6.994  0.95    254.56    321.17
Qwen2.5-1.5B-Instruct (ctx)       69.028  2.87   5555.14  15010.58
Qwen2.5-3B-Instruct (ctx)          5.836  0.88    207.96    310.39
Qwen2.5-7B-Instruct (ctx)          7.212  0.81    226.85    293.10

In [8]:
pd.concat([metrics_no_ctx['overall_metrics'], metrics_ctx['overall_metrics']], axis=0).sort_index()

                                   WMAPE  CRPS       MAE      RMSE
Model
Llama-3.1-8B-Instruct              7.351  0.80    353.14    451.14
Llama-3.1-8B-Instruct (ctx)        6.720  0.73    346.06    457.43
Llama-3.2-1B-Instruct             23.602  1.89  15542.52  28648.61
Llama-3.2-1B-Instruct (ctx)       32.630  4.33  19170.62  32129.55
Llama-3.2-3B-Instruct             11.786  1.06    615.62    905.22
Llama-3.2-3B-Instruct (ctx)        7.031  0.50    813.45    926.40
Ministral-8B-Instruct-2410         6.675  0.92    187.51    235.59
Ministral-8B-Instruct-2410 (ctx)   6.994  0.95    254.56    321.17
Qwen2.5-1.5B-Instruct             14.429  0.64    556.18    773.48
Qwen2.5-1.5B-Instruct (ctx)       69.028  2.87   5555.14  15010.58
Qwen2.5-3B-Instruct                6.211  0.91    239.08    325.84
Qwen2.5-3B-Instruct (ctx)          5.836  0.88    207.96    310.39
Qwen2.5-7B-Instruct                6.613  0.76    226.24    280.10
Qwen2.5-7B-Instruct (ctx)          7.212  0.81    226.85    293.10

In [26]:
# View all metrics, grouped by dataset
# metrics['overall_datasets']

# Query a particular metric:
# metrics['overall_datasets'].xs("WMAPE", level="Metric")

# Query a particular dataset:
# metrics['overall_datasets'].loc['CES3000000008']

metrics['overall_datasets'].xs("WMAPE", level="Metric")

,Llama-3.1-8B-Instruct,Llama-3.2-1B-Instruct,Llama-3.2-3B-Instruct,Ministral-8B-Instruct-2410,Qwen2.5-1.5B-Instruct,Qwen2.5-3B-Instruct,Qwen2.5-7B-Instruct
Dataset,,,,,,,
CES3000000008,0.32,14.11,2.04,0.18,0.44,0.19,0.15
CPIAPPSL,1.57,2.44,1.48,1.69,0.77,1.40,1.40
CUSR0000SA0L5,1.52,9.23,1.48,0.88,0.96,1.04,0.75
DMANEMP,0.75,17.34,1.06,0.69,1.01,0.79,0.53
DTCOLNVHFNM,0.51,27.24,0.65,0.26,0.33,0.31,0.32
NONBORRES,1.68,5.95,7.23,5.49,3.04,6.58,5.82
NONREVSL,0.56,1.78,0.66,0.43,0.33,0.08,0.49
REALLN,1.11,1.71,1.68,0.72,0.67,1.23,0.61
T10YFFM,55.78,148.95,97.58,41.74,126.49,39.49,38.03
UEMP15T26,9.71,7.27,4.00,14.67,10.25,11.00,18.03

In [7]:
# drill into actual forecast data
print(results_ctx['Llama-3.2-1B-Instruct']['dataset_info']['CES3000000008'])
results_ctx['Llama-3.2-1B-Instruct']['results']['CES3000000008']

ID: CES3000000008
Title: Average Hourly Earnings of Production and Nonsupervisory Employees, Manufacturing
Frequency: MS
Date Range: 1939-01-01 to 2024-11-01
Values: 1031 -> 48

,date,forecast_1,forecast_2,forecast_3,forecast_4,forecast_5,forecast_6,forecast_7,forecast_8,forecast_9,forecast_10,forecast_11,forecast_12,forecast_13,forecast_14,forecast_15,value
0,2024-06-01,31.85,32.0,30,29.65,35,30,0.01,26.50,28,21.3,28.1,28.11,20,31.00,28,27.79
1,2024-07-01,31.95,32.1,31,30.05,36,32,0.02,26.85,28,21.6,28.1,28.26,21,31.35,28,27.96
2,2024-08-01,32.05,32.2,32,30.25,37,34,0.03,27.15,29,22.0,28.3,28.42,22,31.55,28,27.97
3,2024-09-01,32.15,32.3,33,30.60,38,36,0.04,27.35,29,21.7,28.4,28.65,23,31.75,28,28.11
4,2024-10-01,32.25,32.5,34,31.05,39,38,0.06,27.55,29,21.8,28.6,28.83,24,31.95,28,28.18
5,2024-11-01,32.35,32.8,35,31.35,40,40,0.07,27.75,30,21.9,28.8,28.98,25,32.15,28,28.30

In [11]:
metrics_no_ctx['overall_timesteps'].xs("WMAPE", level="Metric")

                               t_1     t_2     t_3     t_4     t_5     t_6
Model
Llama-3.1-8B-Instruct        6.997   5.819   8.019   8.023   9.052  22.011
Llama-3.2-1B-Instruct       25.368  25.060  23.305  23.946  29.171  51.742
Llama-3.2-3B-Instruct       14.640  11.990  11.482  11.827  13.845  25.795
Ministral-8B-Instruct-2410   3.528   3.643   6.402   5.534   7.159  29.962
Qwen2.5-1.5B-Instruct       15.889  15.514  14.860  14.304  15.624  27.974
Qwen2.5-3B-Instruct          5.614   4.515   3.737   3.844   9.898  33.906
Qwen2.5-7B-Instruct          3.761   4.413   7.397   7.024   5.803  20.359